# Generated by Django 5.1 on 2025-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Untitled', max_length=250),
        ),
    ]
